module InterfiCapital::Dto
  # Nothing much to do here yet, we use this as a logical grouping to map to the API, which refers to DTOs
end

require 'interfi_capital/dto/error'
require 'interfi_capital/dto/base'
require 'interfi_capital/dto/account'
require 'interfi_capital/dto/address'
require 'interfi_capital/dto/asset'
require 'interfi_capital/dto/bank_account'
require 'interfi_capital/dto/contact'
require 'interfi_capital/dto/direct_debit'
require 'interfi_capital/dto/disbursement'
require 'interfi_capital/dto/employment'
require 'interfi_capital/dto/existing_mortgage'
require 'interfi_capital/dto/expense'
require 'interfi_capital/dto/fee'
require 'interfi_capital/dto/financial_application'
require 'interfi_capital/dto/government_identifier'
require 'interfi_capital/dto/identification_document'
require 'interfi_capital/dto/income'
require 'interfi_capital/dto/ineligibility'
require 'interfi_capital/dto/instalment'
require 'interfi_capital/dto/liability'
require 'interfi_capital/dto/mortgage_insurance'
require 'interfi_capital/dto/offset'
require 'interfi_capital/dto/offset_association'
require 'interfi_capital/dto/other_security'
require 'interfi_capital/dto/party'
require 'interfi_capital/dto/property_security'
require 'interfi_capital/dto/rate_component'
require 'interfi_capital/dto/schedule_repayment'
require 'interfi_capital/dto/tag'
require 'interfi_capital/dto/vehicle_security'
